### PR TITLE
Make it possible to get random quote

### LINKED ISSUE #58: Problem getting random quote
It is not possible to request random quotes. This behaviour started with commit c6be662f72d3eabfbf1c0e175f0fdcab7187b84f.

### PR DESCRIPTION
**Pull request by NilEis**
Closes #58

### CODE REVIEW

**Comment by the-codeboy** [comment]
Why is there a merge commit in this pr? This makes the log ugly

**Review by the-codeboy — COMMENTED** [review]
While this solves the problem for this particular command the actual problem is a different one. The getArgs method used to return an empty array when there were no arguments and now it returns an array containing an empty string. I think it would be way more intuitive to check for an empty string in the getArgs method so this problem does not arise in other commands in the future

**Comment by NilEis** [comment]
☝️🤓

**Comment by NilEis** [comment]
I rewrote it. Do you mean like in the last commit? @the-codeboy

**Pull request merged**
